#include <vector>
#include <list>
#include <map>
#include <set>
#include <queue>
#include <deque>
#include <stack>
#include <bitset>
#include <algorithm>
#include <functional>
#include <numeric>
#include <utility>
#include <sstream>
#include <iostream>
#include <iomanip>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <string.h>

#define rep(i,n) for(int i=0; i<n; i++)
#define reps(i,m,n) for(int i=m; i<n; i++)
#define repe(i,m,n) for(int i=m; i<=n; i++)
#define repi(it,stl) for(typeof((stl).begin()) it = (stl).begin(); (it)!=stl.end(); ++(it))
#define sz(a) ((int)(a).size())
#define mem(a,n) memset((a), (n), sizeof(a))
#define all(n) (n).begin(),(n).end()
#define rall(n) (n).rbegin(),(n).rend()
#define mp(a,b) make_pair((a),(b))
#define pii pair<int,int>
#define vi vector<int>
#define vs vector<string>
#define sstr stringstream 
#define fnd(v,x) (find(all((v)),(x))!=(v).end())
#define itr(A,B) typeof(B) A = B

typedef long long ll;
using namespace std;


class Iditarod {
public:
    int avgMinutes(vector <string> times) {
        int sum=0;
        rep(i,sz(times)){
            int h,m,n;
            char c;
            sscanf(times[i].c_str(),"%d:%d %cM, DAY %d",&h,&m,&c,&n);
            if(c == 'P' && h<12) h+=12;
            if(c == 'A' && h==12) h=0;
            m += n*24*60+h*60;
            m -= 1*24*60+8*60;
            sum += m;
        }
        return round((double)sum/sz(times));
    }
};


// BEGIN KAWIGIEDIT TESTING
// Generated by KawigiEdit 2.1.8 (beta) modified by pivanof
#include <iostream>
#include <string>
#include <vector>
using namespace std;
bool KawigiEdit_RunTest(int testNum, vector <string> p0, bool hasAnswer, int p1) {
    cout << "Test " << testNum << ": [" << "{";
    for (int i = 0; int(p0.size()) > i; ++i) {
        if (i > 0) {
            cout << ",";
        }
        cout << "\"" << p0[i] << "\"";
    }
    cout << "}";
    cout << "]" << endl;
    Iditarod *obj;
    int answer;
    obj = new Iditarod();
    clock_t startTime = clock();
    answer = obj->avgMinutes(p0);
    clock_t endTime = clock();
    delete obj;
    bool res;
    res = true;
    cout << "Time: " << double(endTime - startTime) / CLOCKS_PER_SEC << " seconds" << endl;
    if (hasAnswer) {
        cout << "Desired answer:" << endl;
        cout << "\t" << p1 << endl;
    }
    cout << "Your answer:" << endl;
    cout << "\t" << answer << endl;
    if (hasAnswer) {
        res = answer == p1;
    }
    if (!res) {
        cout << "DOESN'T MATCH!!!!" << endl;
    } else if (double(endTime - startTime) / CLOCKS_PER_SEC >= 2) {
        cout << "FAIL the timeout" << endl;
        res = false;
    } else if (hasAnswer) {
        cout << "Match :-)" << endl;
    } else {
        cout << "OK, but is it right?" << endl;
    }
    cout << "" << endl;
    return res;
}
int main() {
    bool all_right;
    all_right = true;

    vector <string> p0;
    int p1;

    {
	// ----- test 0 -----
	string t0[] = {"12:00 PM, DAY 1","12:01 PM, DAY 1"};
        p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = 241;
	all_right = KawigiEdit_RunTest(0, p0, true, p1) && all_right;
	// ------------------
    }

    {
	// ----- test 1 -----
	string t0[] = {"12:00 AM, DAY 2"};
        p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = 960;
	all_right = KawigiEdit_RunTest(1, p0, true, p1) && all_right;
	// ------------------
    }

    {
	// ----- test 2 -----
	string t0[] = {"02:00 PM, DAY 19","02:00 PM, DAY 20","01:58 PM, DAY 20"};
        p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = 27239;
	all_right = KawigiEdit_RunTest(2, p0, true, p1) && all_right;
	// ------------------
    }

    if (all_right) {
        cout << "You're a stud (at least on the example cases)!" << endl;
    } else {
        cout << "Some of the test cases had errors." << endl;
    }
    return 0;
}
// END KAWIGIEDIT TESTING





//Powered by KawigiEdit 2.1.8 (beta) modified by pivanof!
