#include <vector>
#include <list>
#include <map>
#include <set>
#include <queue>
#include <deque>
#include <stack>
#include <bitset>
#include <algorithm>
#include <functional>
#include <numeric>
#include <utility>
#include <sstream>
#include <iostream>
#include <iomanip>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <string.h>

#define rep(i,n) for(int i=0; i<n; i++)
#define repa(i,a,b,d) for(int i=a; i<=b; i+=d)
#define repd(i,a,b,d) for(int i=a; i>=b; i-=d)
#define repi(it,stl) for(typeof((stl).begin()) it = (stl).begin(); (it)!=stl.end(); ++(it))
#define sz(a) ((int)(a).size())
#define mem(a,n) memset((a), (n), sizeof(a))
#define all(n) (n).begin(),(n).end()
#define rall(n) (n).rbegin(),(n).rend()
#define mp(a,b) make_pair((a),(b))
#define pii pair<int,int>
#define vi vector<int>
#define vs vector<string>
#define sstr stringstream
#define find(v,x) (find(all((v)),(x))-(v).begin())
#define itr(A,B) typeof(B) A = B

typedef long long ll;
using namespace std;

class Islands
{
public:
    int beachLength(vector <string> kingdom) {
        int res = 0;
        rep(i, sz(kingdom)) {
            rep(j, sz(kingdom[i])) {
                if(kingdom[i][j] == '.') continue;
                if(j > 0 && kingdom[i][j - 1] == '.') ++res;
                if(j < sz(kingdom[i]) - 1 && kingdom[i][j + 1] == '.') ++res;
                if((i & 1) == 0) {
                    if(i > 0 && kingdom[i - 1][j] == '.') ++ res;
                    if(i > 0 && j > 0 && kingdom[i - 1][j - 1] == '.') ++ res;
                    if(i + 1 < sz(kingdom) && kingdom[i + 1][j] == '.') ++ res;
                    if(i + 1 < sz(kingdom) && j > 0 && kingdom[i + 1][j - 1] == '.') ++ res;
                } else {
                    if(i > 0 && kingdom[i - 1][j] == '.') ++ res;
                    if(i > 0 && j + 1 < sz(kingdom[i]) && kingdom[i - 1][j + 1] == '.') ++ res;
                    if(i + 1 < sz(kingdom) && kingdom[i + 1][j] == '.') ++ res;
                    if(i + 1 < sz(kingdom) && j + 1 < sz(kingdom[i]) && kingdom[i + 1][j + 1] == '.') ++ res;
                }
            }
        }
        return res;
    }
};


// BEGIN KAWIGIEDIT TESTING
// Generated by KawigiEdit 2.1.8 (beta) modified by pivanof
#include <iostream>
#include <string>
#include <vector>
using namespace std;
bool KawigiEdit_RunTest(int testNum, vector <string> p0, bool hasAnswer, int p1)
{
    cout << "Test " << testNum << ": [" << "{";
    for(int i = 0; int(p0.size()) > i; ++i) {
        if(i > 0) {
            cout << ",";
        }
        cout << "\"" << p0[i] << "\"";
    }
    cout << "}";
    cout << "]" << endl;
    Islands *obj;
    int answer;
    obj = new Islands();
    clock_t startTime = clock();
    answer = obj->beachLength(p0);
    clock_t endTime = clock();
    delete obj;
    bool res;
    res = true;
    cout << "Time: " << double(endTime - startTime) / CLOCKS_PER_SEC << " seconds" << endl;
    if(hasAnswer) {
        cout << "Desired answer:" << endl;
        cout << "\t" << p1 << endl;
    }
    cout << "Your answer:" << endl;
    cout << "\t" << answer << endl;
    if(hasAnswer) {
        res = answer == p1;
    }
    if(!res) {
        cout << "DOESN'T MATCH!!!!" << endl;
    } else if(double(endTime - startTime) / CLOCKS_PER_SEC >= 2) {
        cout << "FAIL the timeout" << endl;
        res = false;
    } else if(hasAnswer) {
        cout << "Match :-)" << endl;
    } else {
        cout << "OK, but is it right?" << endl;
    }
    cout << "" << endl;
    return res;
}
int main()
{
    bool all_right;
    all_right = true;

    vector <string> p0;
    int p1;

    {
        // ----- test 0 -----
        string t0[] = {".#...#.."};
        p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
        p1 = 4;
        all_right = KawigiEdit_RunTest(0, p0, true, p1) && all_right;
        // ------------------
    }

    {
        // ----- test 1 -----
        string t0[] = {"..#.##", ".##.#.", "#.#..."};
        p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
        p1 = 19;
        all_right = KawigiEdit_RunTest(1, p0, true, p1) && all_right;
        // ------------------
    }

    {
        // ----- test 2 -----
        string t0[] = {"#...#.....", "##..#...#."};
        p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
        p1 = 15;
        all_right = KawigiEdit_RunTest(2, p0, true, p1) && all_right;
        // ------------------
    }

    {
        // ----- test 3 -----
        string t0[] = {"....#.", ".#....", "..#..#", "####.."};
        p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
        p1 = 24;
        all_right = KawigiEdit_RunTest(3, p0, true, p1) && all_right;
        // ------------------
    }

    if(all_right) {
        cout << "You're a stud (at least on the example cases)!" << endl;
    } else {
        cout << "Some of the test cases had errors." << endl;
    }
    return 0;
}
// END KAWIGIEDIT TESTING







//Powered by KawigiEdit 2.1.8 (beta) modified by pivanof!
